class Sq(name: String) {
    val coords: Coords

    init {
        when (name) {
            "a8" -> coords = Coords(0, 0)
            "a7" -> coords = Coords(0, 1)
            "a6" -> coords = Coords(0, 2)
            "a5" -> coords = Coords(0, 3)
            "a4" -> coords = Coords(0, 4)
            "a3" -> coords = Coords(0, 5)
            "a2" -> coords = Coords(0, 6)
            "a1" -> coords = Coords(0, 7)
            "b8" -> coords = Coords(1, 0)
            "b7" -> coords = Coords(1, 1)
            "b6" -> coords = Coords(1, 2)
            "b5" -> coords = Coords(1, 3)
            "b4" -> coords = Coords(1, 4)
            "b3" -> coords = Coords(1, 5)
            "b2" -> coords = Coords(1, 6)
            "b1" -> coords = Coords(1, 7)
            "c8" -> coords = Coords(2, 0)
            "c7" -> coords = Coords(2, 1)
            "c6" -> coords = Coords(2, 2)
            "c5" -> coords = Coords(2, 3)
            "c4" -> coords = Coords(2, 4)
            "c3" -> coords = Coords(2, 5)
            "c2" -> coords = Coords(2, 6)
            "c1" -> coords = Coords(2, 7)
            "d8" -> coords = Coords(3, 0)
            "d7" -> coords = Coords(3, 1)
            "d6" -> coords = Coords(3, 2)
            "d5" -> coords = Coords(3, 3)
            "d4" -> coords = Coords(3, 4)
            "d3" -> coords = Coords(3, 5)
            "d2" -> coords = Coords(3, 6)
            "d1" -> coords = Coords(3, 7)
            "e8" -> coords = Coords(4, 0)
            "e7" -> coords = Coords(4, 1)
            "e6" -> coords = Coords(4, 2)
            "e5" -> coords = Coords(4, 3)
            "e4" -> coords = Coords(4, 4)
            "e3" -> coords = Coords(4, 5)
            "e2" -> coords = Coords(4, 6)
            "e1" -> coords = Coords(4, 7)
            "f8" -> coords = Coords(5, 0)
            "f7" -> coords = Coords(5, 1)
            "f6" -> coords = Coords(5, 2)
            "f5" -> coords = Coords(5, 3)
            "f4" -> coords = Coords(5, 4)
            "f3" -> coords = Coords(5, 5)
            "f2" -> coords = Coords(5, 6)
            "f1" -> coords = Coords(5, 7)
            "g8" -> coords = Coords(6, 0)
            "g7" -> coords = Coords(6, 1)
            "g6" -> coords = Coords(6, 2)
            "g5" -> coords = Coords(6, 3)
            "g4" -> coords = Coords(6, 4)
            "g3" -> coords = Coords(6, 5)
            "g2" -> coords = Coords(6, 6)
            "g1" -> coords = Coords(6, 7)
            "h8" -> coords = Coords(7, 0)
            "h7" -> coords = Coords(7, 1)
            "h6" -> coords = Coords(7, 2)
            "h5" -> coords = Coords(7, 3)
            "h4" -> coords = Coords(7, 4)
            "h3" -> coords = Coords(7, 5)
            "h2" -> coords = Coords(7, 6)
            "h1" -> coords = Coords(7, 7)
            else -> throw IllegalArgumentException("Invalid square name: $name")
        }
    }
}