package engine.v1

class Sq(name: String) {
    val xy: Coords

    init {
        when (name) {
            "a8" -> xy = Coords(0, 0)
            "a7" -> xy = Coords(0, 1)
            "a6" -> xy = Coords(0, 2)
            "a5" -> xy = Coords(0, 3)
            "a4" -> xy = Coords(0, 4)
            "a3" -> xy = Coords(0, 5)
            "a2" -> xy = Coords(0, 6)
            "a1" -> xy = Coords(0, 7)
            "b8" -> xy = Coords(1, 0)
            "b7" -> xy = Coords(1, 1)
            "b6" -> xy = Coords(1, 2)
            "b5" -> xy = Coords(1, 3)
            "b4" -> xy = Coords(1, 4)
            "b3" -> xy = Coords(1, 5)
            "b2" -> xy = Coords(1, 6)
            "b1" -> xy = Coords(1, 7)
            "c8" -> xy = Coords(2, 0)
            "c7" -> xy = Coords(2, 1)
            "c6" -> xy = Coords(2, 2)
            "c5" -> xy = Coords(2, 3)
            "c4" -> xy = Coords(2, 4)
            "c3" -> xy = Coords(2, 5)
            "c2" -> xy = Coords(2, 6)
            "c1" -> xy = Coords(2, 7)
            "d8" -> xy = Coords(3, 0)
            "d7" -> xy = Coords(3, 1)
            "d6" -> xy = Coords(3, 2)
            "d5" -> xy = Coords(3, 3)
            "d4" -> xy = Coords(3, 4)
            "d3" -> xy = Coords(3, 5)
            "d2" -> xy = Coords(3, 6)
            "d1" -> xy = Coords(3, 7)
            "e8" -> xy = Coords(4, 0)
            "e7" -> xy = Coords(4, 1)
            "e6" -> xy = Coords(4, 2)
            "e5" -> xy = Coords(4, 3)
            "e4" -> xy = Coords(4, 4)
            "e3" -> xy = Coords(4, 5)
            "e2" -> xy = Coords(4, 6)
            "e1" -> xy = Coords(4, 7)
            "f8" -> xy = Coords(5, 0)
            "f7" -> xy = Coords(5, 1)
            "f6" -> xy = Coords(5, 2)
            "f5" -> xy = Coords(5, 3)
            "f4" -> xy = Coords(5, 4)
            "f3" -> xy = Coords(5, 5)
            "f2" -> xy = Coords(5, 6)
            "f1" -> xy = Coords(5, 7)
            "g8" -> xy = Coords(6, 0)
            "g7" -> xy = Coords(6, 1)
            "g6" -> xy = Coords(6, 2)
            "g5" -> xy = Coords(6, 3)
            "g4" -> xy = Coords(6, 4)
            "g3" -> xy = Coords(6, 5)
            "g2" -> xy = Coords(6, 6)
            "g1" -> xy = Coords(6, 7)
            "h8" -> xy = Coords(7, 0)
            "h7" -> xy = Coords(7, 1)
            "h6" -> xy = Coords(7, 2)
            "h5" -> xy = Coords(7, 3)
            "h4" -> xy = Coords(7, 4)
            "h3" -> xy = Coords(7, 5)
            "h2" -> xy = Coords(7, 6)
            "h1" -> xy = Coords(7, 7)
            else -> throw IllegalArgumentException("Invalid square name: $name")
        }
    }
}